apiVersion: apps/v1
kind: Deployment
metadata:
  name: pii-redaction-service
  labels:
    app: pii-redaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pii-redaction-service
  template:
    metadata:
      labels:
        app: pii-redaction-service
    spec:
      containers:
      - name: pii-redaction-service
        image: your-docker-registry/pii-redaction-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: "/app"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
