apiVersion: v1
kind: Service
metadata:
  name: pii-redaction-service
  labels:
    app: pii-redaction-service
spec:
  selector:
    app: pii-redaction-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: pii-redaction-service-external
  labels:
    app: pii-redaction-service
spec:
  selector:
    app: pii-redaction-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
